python:
  label: Python
  permalink: /python
  description: Python articles

welcome:
  label: Hello
  permalink: /hello
  description: Hello tag

software-development:
  label: Software Development
  permalink: /software-dev
  description: Software Development articles

devops:
  label: DevOps
  permalink: /devops
  description: Devops Articles

automation:
  label: Automation
  permalink: /automation
  description: Automation articles

testing:
  label: Testing
  permalink: /testing
  description: Testing articles

bdd:
  label: Behavior-Driven Development
  permalink: /bdd
  description: Behavior-Driven Development

about:
  label: About
  permalink: /about
  description: About me articles
